### ISSUE TITLE
4 player system crashes

### ISSUE THREAD

**Issue by lbwtaylor** [DeathDealer33/Halo-Online-Splitscreen-Tool-V1.1#2]
Hello,

First thank you for keeping this tool up to date, it is very much appreciated.

I can get 2 and 3 player splitsreen working reliably. But when I do 4, windows stalls/locks, typically when I choose start game in the lobby. I have added the 1200 cache. Any ideas?

Thanks
Lawrence

**Comment by MrAngularVelocity** [comment]
From other splitscreen tools, the same issue occurs. I know the current work around is to have one player join late and exit early to avoid having all 4 players enter the load screen at once!

**Comment by lbwtaylor** [comment]
Thanks very much for this response.

**Comment by DeathDealer33** [comment]
You can change" HandlerInterval = ('15000')#15 seconds" to a higher value. This will give more time for each instance to boot and setup.
