### ISSUE TITLE
Xinput order with m/kb

### ISSUE THREAD

**Issue by MrAngularVelocity** [DeathDealer33/Halo-Online-Splitscreen-Tool-V1.1#3]
Just thought I should mention that it would be useful to skip xinput player # when a keyboard is used. For example, when player 1 is using a m/kb, the P1 xinput controller is effectively useless, and P2 is set to Xinput 2.

I also found another bug where P4 will not be assigned to Xinput 4 sometimes (and Xinput 2 controls two screens at once).

**Comment by DeathDealer33** [comment]
Gamepad should be disabled when keyboard mouse is used for that instance. I need to be able to replicate the issue or i cannot fix it. Make sure when the program is setting up you do not click anything or press any buttons.
